//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatter.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatHistory
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int SenderUserID { get; set; }
        public int RecipientUserID { get; set; }
    }
}
